#!/usr/bin/env perl
use lib 't/lib';
use Test::NetHack::Items (
    "x - 100 gold pieces",                             {type => "other"    },
    "a - a +1 long sword (weapon in hand)",            {type => "weapon"   },
    "b - a blessed +0 dagger",                         {type => "weapon"   },
    "h - 8 +0 darts",                                  {type => "weapon"   },
    "s - a poisoned +0 arrow",                         {type => "weapon"   },
    "p - a +0 boomerang",                              {type => "weapon"   },
    "S - the +0 Cleaver",                              {type => "weapon"   },
    "c - an uncursed +3 small shield (being worn)",    {type => "armor"    },
    "o - an uncursed +0 banded mail",                  {type => "armor"    },
    "q - an uncursed +0 crystal plate mail",           {type => "armor"    },
    "h - the uncursed +0 Mitre of Holiness",           {type => "armor"    },
    "t - a set of gray dragon scales",                 {type => "armor"    },
    "x - an elven mithril-coat",                       {type => "armor"    },
    "d - 2 uncursed food rations",                     {type => "food"     },
    "j - a cursed tin of lichen",                      {type => "food"     },
    "K - an uncursed tin of newt meat",                {type => "food"     },
    "r - an uncursed partly eaten tripe ration",       {type => "food"     },
    "P - a blessed lichen corpse",                     {type => "food"     },
    "R - an uncursed guardian naga egg",               {type => "food"     },
    "w - an uncursed empty tin",                       {type => "food"     },
    "x - A slime mold",                                {type => "food"     },
    "N - an uncursed scroll of blank paper",           {type => "scroll"   },
    "k - an uncursed spellbook of blank paper",        {type => "spellbook"},
    "T - the uncursed Book of the Dead",               {type => "spellbook"},
    "C - an uncursed potion of water",                 {type => "potion"   },
    "k - the Eye of the Aethiopica",                   {type => "amulet"   },
    "U - the Amulet of Yendor",                        {type => "amulet"   },
    "e - a +0 pick-axe",                               {type => "tool"     },
    "f - a +0 grappling hook",                         {type => "tool"     },
    "t - an uncursed large box",                       {type => "tool"     },
    "m - the Master Key of Thievery",                  {type => "tool"     },
    "u - a figurine of a lichen",                      {type => "tool"     },
    "u - 53 rocks",                                    {type => "gem"      },
    "n - the Heart of Ahriman",                        {type => "gem"      },
    "v - a statue of a lichen",                        {type => "other"    },
);

