#!/usr/bin/env perl
use lib 't/lib';
use Test::NetHack::Items (
    "x - a samurai sword",                   {type => "weapon"},
    "y - 5 crude daggers",                   {type => "weapon"},
    "z - a broad pick",                      {type => "weapon"},
    "f - a double-headed axe named Cleaver", {type => "weapon"},
    "s - a poisoned arrow",                  {type => "weapon"},
    "A - a crude ring mail",                 {type => "armor"},
    "B - an apron",                          {type => "armor"},
    "C - a faded pall",                      {type => "armor"},
    "h - a visored helmet named The Mitre of Holiness", {type => "armor"},
    "s - a pair of riding gloves",           {type => "armor"},
    "i - an egg",                            {type => "food"},
    "D - 2 tins",                            {type => "food"},
    "f - a scroll labeled PRATYAVAYAH",      {type => "scroll"},
    "m - a scroll labeled JUYED AWK YACC",   {type => "scroll"},
    "E - 2 scrolls labeled FOOBIE BLETCH",   {type => "scroll"},
    "l - an orange spellbook",               {type => "spellbook"},
    "n - a light blue spellbook",            {type => "spellbook"},
    "u - a magenta spellbook",               {type => "spellbook"},
    "g - a papyrus spellbook",               {type => "spellbook"},
    "N - a murky potion",                    {type => "potion"},
    "O - a sky blue potion",                 {type => "potion"},
    "P - 2 brown potions",                   {type => "potion"},
    "h - a hexagonal amulet",                {type => "amulet"},
    "G - a triangular amulet",               {type => "amulet"},
    "H - a pyramidal amulet",                {type => "amulet"},
    "q - a gold ring",                       {type => "ring"},
    "t - a granite ring",                    {type => "ring"},
    "v - an opal ring",                      {type => "ring"},
    "K - a runed wand",                      {type => "wand"},
    "L - a brass wand",                      {type => "wand"},
    "M - an oak wand",                       {type => "wand"},
    "g - 2 yellow gems",                     {type => "gem"},
    "I - a green gem",                       {type => "gem"},
    "Q - a gray stone",                      {type => "gem"},
);

